/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SendRouteImport } from './routes/send'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as PayRouteImport } from './routes/pay'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FundRouteImport } from './routes/fund'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as SignupVerifyRouteImport } from './routes/signup_.verify'
import { Route as SignupPinRouteImport } from './routes/signup_.pin'
import { Route as SignupCompleteRouteImport } from './routes/signup_.complete'
import { Route as SignupBiometricsRouteImport } from './routes/signup_.biometrics'
import { Route as SettingsPinRouteImport } from './routes/settings_.pin'
import { Route as LoginVerifyRouteImport } from './routes/login_.verify'
import { Route as LoginPhoneRouteImport } from './routes/login_.phone'
import { Route as ClaimRefRouteImport } from './routes/claim.$ref'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyRoute = SignupVerifyRouteImport.update({
  id: '/signup_/verify',
  path: '/signup/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupPinRoute = SignupPinRouteImport.update({
  id: '/signup_/pin',
  path: '/signup/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupCompleteRoute = SignupCompleteRouteImport.update({
  id: '/signup_/complete',
  path: '/signup/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupBiometricsRoute = SignupBiometricsRouteImport.update({
  id: '/signup_/biometrics',
  path: '/signup/biometrics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPinRoute = SettingsPinRouteImport.update({
  id: '/settings_/pin',
  path: '/settings/pin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginVerifyRoute = LoginVerifyRouteImport.update({
  id: '/login_/verify',
  path: '/login/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPhoneRoute = LoginPhoneRouteImport.update({
  id: '/login_/phone',
  path: '/login/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRefRoute = ClaimRefRouteImport.update({
  id: '/claim/$ref',
  path: '/claim/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/pay': typeof PayRoute
  '/receive': typeof ReceiveRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/claim/$ref': typeof ClaimRefRoute
  '/login/phone': typeof LoginPhoneRoute
  '/login/verify': typeof LoginVerifyRoute
  '/settings/pin': typeof SettingsPinRoute
  '/signup/biometrics': typeof SignupBiometricsRoute
  '/signup/complete': typeof SignupCompleteRoute
  '/signup/pin': typeof SignupPinRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/pay': typeof PayRoute
  '/receive': typeof ReceiveRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/claim/$ref': typeof ClaimRefRoute
  '/login/phone': typeof LoginPhoneRoute
  '/login/verify': typeof LoginVerifyRoute
  '/settings/pin': typeof SettingsPinRoute
  '/signup/biometrics': typeof SignupBiometricsRoute
  '/signup/complete': typeof SignupCompleteRoute
  '/signup/pin': typeof SignupPinRoute
  '/signup/verify': typeof SignupVerifyRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRoute
  '/pay': typeof PayRoute
  '/receive': typeof ReceiveRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/claim/$ref': typeof ClaimRefRoute
  '/login_/phone': typeof LoginPhoneRoute
  '/login_/verify': typeof LoginVerifyRoute
  '/settings_/pin': typeof SettingsPinRoute
  '/signup_/biometrics': typeof SignupBiometricsRoute
  '/signup_/complete': typeof SignupCompleteRoute
  '/signup_/pin': typeof SignupPinRoute
  '/signup_/verify': typeof SignupVerifyRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/login'
    | '/merchant'
    | '/pay'
    | '/receive'
    | '/scan'
    | '/send'
    | '/signup'
    | '/wallet'
    | '/claim/$ref'
    | '/login/phone'
    | '/login/verify'
    | '/settings/pin'
    | '/signup/biometrics'
    | '/signup/complete'
    | '/signup/pin'
    | '/signup/verify'
    | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/login'
    | '/merchant'
    | '/pay'
    | '/receive'
    | '/scan'
    | '/send'
    | '/signup'
    | '/wallet'
    | '/claim/$ref'
    | '/login/phone'
    | '/login/verify'
    | '/settings/pin'
    | '/signup/biometrics'
    | '/signup/complete'
    | '/signup/pin'
    | '/signup/verify'
    | '/track/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/login'
    | '/merchant'
    | '/pay'
    | '/receive'
    | '/scan'
    | '/send'
    | '/signup'
    | '/wallet'
    | '/claim/$ref'
    | '/login_/phone'
    | '/login_/verify'
    | '/settings_/pin'
    | '/signup_/biometrics'
    | '/signup_/complete'
    | '/signup_/pin'
    | '/signup_/verify'
    | '/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FundRoute: typeof FundRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRoute
  PayRoute: typeof PayRoute
  ReceiveRoute: typeof ReceiveRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  ClaimRefRoute: typeof ClaimRefRoute
  LoginPhoneRoute: typeof LoginPhoneRoute
  LoginVerifyRoute: typeof LoginVerifyRoute
  SettingsPinRoute: typeof SettingsPinRoute
  SignupBiometricsRoute: typeof SignupBiometricsRoute
  SignupCompleteRoute: typeof SignupCompleteRoute
  SignupPinRoute: typeof SignupPinRoute
  SignupVerifyRoute: typeof SignupVerifyRoute
  TrackIdRoute: typeof TrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/verify': {
      id: '/signup_/verify'
      path: '/signup/verify'
      fullPath: '/signup/verify'
      preLoaderRoute: typeof SignupVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/pin': {
      id: '/signup_/pin'
      path: '/signup/pin'
      fullPath: '/signup/pin'
      preLoaderRoute: typeof SignupPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/complete': {
      id: '/signup_/complete'
      path: '/signup/complete'
      fullPath: '/signup/complete'
      preLoaderRoute: typeof SignupCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/biometrics': {
      id: '/signup_/biometrics'
      path: '/signup/biometrics'
      fullPath: '/signup/biometrics'
      preLoaderRoute: typeof SignupBiometricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings_/pin': {
      id: '/settings_/pin'
      path: '/settings/pin'
      fullPath: '/settings/pin'
      preLoaderRoute: typeof SettingsPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/verify': {
      id: '/login_/verify'
      path: '/login/verify'
      fullPath: '/login/verify'
      preLoaderRoute: typeof LoginVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/phone': {
      id: '/login_/phone'
      path: '/login/phone'
      fullPath: '/login/phone'
      preLoaderRoute: typeof LoginPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$ref': {
      id: '/claim/$ref'
      path: '/claim/$ref'
      fullPath: '/claim/$ref'
      preLoaderRoute: typeof ClaimRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FundRoute: FundRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRoute,
  PayRoute: PayRoute,
  ReceiveRoute: ReceiveRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  ClaimRefRoute: ClaimRefRoute,
  LoginPhoneRoute: LoginPhoneRoute,
  LoginVerifyRoute: LoginVerifyRoute,
  SettingsPinRoute: SettingsPinRoute,
  SignupBiometricsRoute: SignupBiometricsRoute,
  SignupCompleteRoute: SignupCompleteRoute,
  SignupPinRoute: SignupPinRoute,
  SignupVerifyRoute: SignupVerifyRoute,
  TrackIdRoute: TrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
