/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SendRouteImport } from './routes/send'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FundRouteImport } from './routes/fund'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIdRouteImport } from './routes/track.$id'
import { Route as ClaimRefRouteImport } from './routes/claim.$ref'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FundRoute = FundRouteImport.update({
  id: '/fund',
  path: '/fund',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIdRoute = TrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimRefRoute = ClaimRefRouteImport.update({
  id: '/claim/$ref',
  path: '/claim/$ref',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/history': typeof HistoryRoute
  '/merchant': typeof MerchantRoute
  '/receive': typeof ReceiveRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/claim/$ref': typeof ClaimRefRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/history': typeof HistoryRoute
  '/merchant': typeof MerchantRoute
  '/receive': typeof ReceiveRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/claim/$ref': typeof ClaimRefRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/fund': typeof FundRoute
  '/history': typeof HistoryRoute
  '/merchant': typeof MerchantRoute
  '/receive': typeof ReceiveRoute
  '/scan': typeof ScanRoute
  '/send': typeof SendRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/claim/$ref': typeof ClaimRefRoute
  '/track/$id': typeof TrackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/merchant'
    | '/receive'
    | '/scan'
    | '/send'
    | '/signup'
    | '/wallet'
    | '/claim/$ref'
    | '/track/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/merchant'
    | '/receive'
    | '/scan'
    | '/send'
    | '/signup'
    | '/wallet'
    | '/claim/$ref'
    | '/track/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/fund'
    | '/history'
    | '/merchant'
    | '/receive'
    | '/scan'
    | '/send'
    | '/signup'
    | '/wallet'
    | '/claim/$ref'
    | '/track/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  FundRoute: typeof FundRoute
  HistoryRoute: typeof HistoryRoute
  MerchantRoute: typeof MerchantRoute
  ReceiveRoute: typeof ReceiveRoute
  ScanRoute: typeof ScanRoute
  SendRoute: typeof SendRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  ClaimRefRoute: typeof ClaimRefRoute
  TrackIdRoute: typeof TrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fund': {
      id: '/fund'
      path: '/fund'
      fullPath: '/fund'
      preLoaderRoute: typeof FundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$id': {
      id: '/track/$id'
      path: '/track/$id'
      fullPath: '/track/$id'
      preLoaderRoute: typeof TrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claim/$ref': {
      id: '/claim/$ref'
      path: '/claim/$ref'
      fullPath: '/claim/$ref'
      preLoaderRoute: typeof ClaimRefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  FundRoute: FundRoute,
  HistoryRoute: HistoryRoute,
  MerchantRoute: MerchantRoute,
  ReceiveRoute: ReceiveRoute,
  ScanRoute: ScanRoute,
  SendRoute: SendRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  ClaimRefRoute: ClaimRefRoute,
  TrackIdRoute: TrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
